[profile.default]
src = "src"
out = "out"
libs = ["lib"]
bytecode_hash = "none"

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@eigenlayer-middleware/=lib/eigenlayer-middleware/",
    "@eigenlayer-contracts/=lib/eigenlayer-middleware/lib/eigenlayer-contracts/",
    "@openzeppelin/=lib/eigenlayer-middleware/lib/openzeppelin-contracts/",
    "@openzeppelin-upgrades/=lib/eigenlayer-middleware/lib/openzeppelin-contracts-upgradeable/",
]

fs_permissions = [{ access = "read-write", path = "./" }]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

no_match_path = "script/releases/**/*.sol"

ignored_error_codes = [
    # 1878, # license
    5574, # code-size
    # 2018, # func-mutability
    # 2072, # unused-var
    # 5667, # unused-param
    # 9302, # unused-return
    # 5815, # virtual-interfaces
    # 3628, # missing-receive-ether
    # 2519, # shadowing
    # 8760, # same-varname
    # 6321, # unnamed-return
    # 5740, # unreachable
    # 3420, # pragma-solidity
    # 2462, # constructor-visibility
    3860, # init-code-size
    # 2394, # transient-storage
    4591, # too-many-warnings
]
